# Generated by Django 5.0.6 on 2024-07-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='ubicacion',
            field=models.CharField(default='Ubicación no especificada', max_length=255),
        ),
    ]
